version: 2.1

orbs:
  rust: circleci/rust@1.6.0
  github-cli: circleci/github-cli@2.2.0

jobs:
  release:
    docker:
      - image: rust:1.69-buster
    steps:
      - checkout
      - github-cli/install
      - restore_cache:
          key: project-cache
      - run: cd ./target/release/ && tar czvf cinc_server_exporter.tar.gz cinc_server_exporter
      - run: gh release create -R esoterick/cinc_server_exporter -F RELEASE.md "$CIRCLE_TAG" ./target/release/cinc_server_exporter.tar.gz
  build:
    docker:
      - image: rust:1.69-buster
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Install tools
          command: |
            rustup update
            rustup install nightly
            rustup install stable
            rustup default nightly
            rustup component add rustfmt
      - run:
          name: Check formatting
          command: |
            rustfmt --version
            cargo fmt
      # - run:
      #     name: Nightly Build
      #     command: |
      #       rustup run nightly rustc --version --verbose
      #       rustup run nightly cargo --version --verbose
      #       rustup run nightly cargo build
      - run:
          name: Stable Build
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
            rustup run stable cargo build  --release
      - run:
          name: Test
          command: rustup run stable cargo test
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

workflows:
  release-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: main
      - release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
