name: Publish Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install github:cachix/devenv/latest
        shell: sh
      - name: Build the release
        run: devenv shell cargo build --release
        shell: sh
      - name: Create our tarball
        run: |
          ls -latrh target/release
